# Quotes are not necessary.
out_dir = .
interfaces = eth0, wlan0, lo
filter = ether proto 0x88f7

# trigerror supports underscores for number group separators.
count_before = 1_000
time_before = 5_000
count_after = 1_000
time_after = 5_000

retrigger = false
max_retriggers = 10
