out_dir = "."
interfaces = wlan0, eth0, lo
; interfaces = enp0s13f0u3u2i5
protocols = ptp, http
# TODO: this should be a BPF compliant string
# TODO: test dns
; filter = tcp
count_before = 10
time_before = 10000
count_after = 20
time_after = 10000
file_size = 1
retrigger = false
# max_retriggers = 9
; TODO: max file size (calculate from packets captured)
