out_dir = "."
interfaces = wlan0, eth0, lo
; interfaces = enp0s13f0u3u2i5
protocols = ptp, http
# TODO: this should be a BPF compliant string
# TODO: test dns
; filter = tcp
count_before = 20
count_after = 30
; time_before = 19
; time_after = 49
file_size = 1
retrigger = true
# max_retriggers = 9
; TODO: max file size (calculate from packets captured)
